# Generated by Django 5.2.6 on 2025-10-05 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_examtimetable_teachernotification_dailytimetable"),
        ("teachers", "0002_teachersalary"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="class_teacher",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_teacher_of",
                to="teachers.teacher",
            ),
        ),
    ]
