# Generated by Django 5.2.6 on 2025-10-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_classroom_class_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_no",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GENERAL", "General"),
                    ("OBC", "Obc"),
                    ("SC", "Sc"),
                    ("ST", "St"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="father_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="mother_name",
            field=models.CharField(max_length=100),
        ),
    ]
