# Generated by Django 5.2.6 on 2025-10-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_student_admission_no_alter_student_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_no",
            field=models.CharField(max_length=50),
        ),
    ]
