# Generated by Django 5.2.6 on 2025-10-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_alter_student_admission_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatetype",
            name="html_template",
            field=models.TextField(
                blank=True,
                help_text="HTML template with placeholders like {{student_name}}, {{class}}, {{date}}",
            ),
        ),
    ]
