# Generated by Django 5.2.6 on 2025-10-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_certificatetype_html_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="plain_text_password",
            field=models.CharField(
                blank=True,
                help_text="Plain text password for admin reference",
                max_length=128,
            ),
        ),
    ]
