# Generated by Django 5.2.6 on 2025-10-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_plain_text_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
