[project]
name = "schoolsite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.6",
    "django-browser-reload>=1.21.0",
    "pillow>=11.3.0",
    "psycopg2>=2.9.10",
    "reportlab>=4.4.4",
]
