# Generated by Django 5.2.6 on 2025-10-01 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField()),
                ("section", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr_no", models.IntegerField()),
                ("roll_no", models.IntegerField()),
                ("admission_no", models.CharField()),
                ("father_name", models.CharField()),
                ("mother_name", models.CharField()),
                ("dob", models.DateField()),
                ("mobile_no", models.BigIntegerField()),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GENERAL", "General"),
                            ("OBC", "Obc"),
                            ("SC", "Sc"),
                            ("ST", "St"),
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(choices=[("MALE", "Male"), ("FEMALE", "Female")]),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to="dashboard.classroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
