# Generated by Django 5.2.6 on 2025-10-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="students/<django.db.models.fields.IntegerField>/profile",
            ),
        ),
    ]
