# Generated by Django 5.2.6 on 2025-10-01 09:54

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_student_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=dashboard.models.student_profile_photo_path,
            ),
        ),
    ]
