# Generated by Django 5.2.6 on 2025-10-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_certificatetype_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
            ),
        ),
    ]
