# Generated by Django 5.2.6 on 2025-10-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_stream_subject_student_stream_student_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="current_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="permanent_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="section",
            field=models.CharField(blank=True, null=True),
        ),
    ]
