# Generated by Django 5.2.6 on 2025-10-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="notice_type",
            field=models.CharField(
                choices=[
                    ("ANNOUNCEMENT", "Announcement"),
                    ("INDIVIDUAL", "Individual"),
                ],
                default="ANNOUNCEMENT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="target_students",
            field=models.ManyToManyField(
                blank=True,
                help_text="For individual notices, select which students this applies to",
                related_name="individual_notices",
                to="dashboard.student",
            ),
        ),
    ]
