# Generated by Django 5.2.6 on 2025-10-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_notice_notice_type_notice_target_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="admit_card_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_yearly_final",
            field=models.BooleanField(default=False),
        ),
    ]
