# Generated by Django 5.2.6 on 2025-10-02 08:08

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_teacherattendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=dashboard.models.teacher_profile_photo_path,
            ),
        ),
    ]
