# Generated by Django 5.2.6 on 2025-10-08 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0001_initial"),
        ("students", "0005_alter_student_admission_no"),
        ("teachers", "0002_teachersalary"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="target_class",
            field=models.ForeignKey(
                blank=True,
                help_text="For class-specific notices",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_notices",
                to="students.classroom",
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="target_teachers",
            field=models.ManyToManyField(
                blank=True,
                help_text="For individual teacher notices",
                related_name="individual_notices",
                to="teachers.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="notice_type",
            field=models.CharField(
                choices=[
                    ("ALL_STUDENTS", "All Students"),
                    ("CLASS_STUDENTS", "Specific Class"),
                    ("INDIVIDUAL_STUDENT", "Individual Student"),
                    ("ALL_TEACHERS", "All Teachers"),
                    ("INDIVIDUAL_TEACHER", "Individual Teacher"),
                ],
                default="ALL_STUDENTS",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="target_students",
            field=models.ManyToManyField(
                blank=True,
                help_text="For individual student notices",
                related_name="individual_notices",
                to="students.student",
            ),
        ),
    ]
