# Generated by Django 5.2.6 on 2025-10-10 02:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0002_notice_target_class_notice_target_teachers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="dismissed_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have dismissed this notice",
                related_name="dismissed_notices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="notice_type",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public Announcement"),
                    ("ALL_STUDENTS", "All Students"),
                    ("CLASS_STUDENTS", "Specific Class"),
                    ("INDIVIDUAL_STUDENT", "Individual Student"),
                    ("ALL_TEACHERS", "All Teachers"),
                    ("INDIVIDUAL_TEACHER", "Individual Teacher"),
                ],
                default="ALL_STUDENTS",
                max_length=20,
            ),
        ),
    ]
