# Generated by Django 5.2.6 on 2025-10-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0003_notice_dismissed_by_alter_notice_notice_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="notice_type",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public Announcement"),
                    ("ALL_STUDENTS", "All Students"),
                    ("CLASS_STUDENTS", "Specific Class"),
                    ("INDIVIDUAL_STUDENT", "Individual Student"),
                    ("ALL_TEACHERS", "All Teachers"),
                    ("INDIVIDUAL_TEACHER", "Individual Teacher"),
                    ("SYSTEM_ALERT", "System Alert"),
                ],
                default="ALL_STUDENTS",
                max_length=20,
            ),
        ),
    ]
