# Generated by Django 5.2.6 on 2025-10-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_alter_examresult_status_examassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="marking_disabled",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this result field cannot be edited",
            ),
        ),
    ]
