# Generated by Django 5.2.6 on 2025-10-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_examresult_marking_disabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("LOCKED", "Locked"),
                    ("PUBLISHED", "Published"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
