# Generated by Django 5.2.6 on 2025-10-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_alter_examresult_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="marks_entry_open",
            field=models.BooleanField(
                default=False,
                help_text="Whether teachers can enter marks for this exam",
            ),
        ),
    ]
