# Generated by Django 5.2.6 on 2025-10-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0002_teachersalary"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="plain_text_password",
            field=models.CharField(
                blank=True,
                help_text="Plain text password for admin reference",
                max_length=255,
                null=True,
            ),
        ),
    ]
