# Generated by Django 5.2.6 on 2025-10-08 02:23

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Display title for the carousel image", max_length=200
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Carousel image (recommended: 1920x800px)",
                        upload_to=base.models.carousel_image_path,
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, help_text="Optional caption text", max_length=300
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True, help_text="Optional link URL when image is clicked"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of display (lower numbers appear first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Show this image in carousel"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Carousel Image",
                "verbose_name_plural": "Carousel Images",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Image title", max_length=200)),
                (
                    "image",
                    models.ImageField(
                        help_text="Gallery image",
                        upload_to=base.models.gallery_image_path,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("school", "School Activities"),
                            ("events", "Events"),
                            ("achievements", "Achievements"),
                            ("facilities", "Facilities"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of display"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Show this image in gallery"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PopupImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Popup title", max_length=200)),
                (
                    "image",
                    models.ImageField(
                        help_text="Popup image (recommended: 800x600px)",
                        upload_to=base.models.popup_image_path,
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True, help_text="Optional link URL when image is clicked"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Show this popup (only one can be active at a time)",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to start showing the popup",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to stop showing the popup",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Popup Image",
                "verbose_name_plural": "Popup Images",
                "ordering": ["-created_at"],
            },
        ),
    ]
